# Generated by Django 4.1 on 2022-11-29 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='categoriaNome',
            new_name='categoria',
        ),
    ]
