# Generated by Django 4.1 on 2022-11-30 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_rename_categorianome_categoria_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categorias',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.categoria'),
        ),
    ]
